GruppenarbeitTillChristian/src/application/filemanager/FileOverviewBean.java
package application.filemanager;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import javax.activation.MimetypesFileTypeMap;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.primefaces.event.DragDropEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import application.database.MongoConst;
import application.database.MongoFileAO;
import application.session.UserSession;

@ManagedBean
@ViewScoped
public class FileOverviewBean {
	@ManagedProperty(value="#{mongoFileAO}")
	private MongoFileAO fileAO;

	@ManagedProperty(value="#{userSession}")
	private UserSession userSession;
	
	private List<ShowFile> dropedFiles;
	private FileDataModel fileDataModel;
	private ShowFile selectedFile;
	
	public FileOverviewBean() {}
	
	@PostConstruct
	private void fileOverviewBeanConstructor() {
		fileDataModel = new FileDataModel(
				fileAO.getFileNamesFor(
						userSession.getUsername()));
		dropedFiles = new ArrayList<ShowFile>();
	}
	
	public void onDropFile(DragDropEvent ddEvent) {
		ShowFile showFile = (ShowFile)ddEvent.getData();
		dropedFiles.add(showFile);
	}
	
	public UserSession getUserSession() {
		return userSession;
	}

	public void setUserSession(UserSession userSession) {
		this.userSession = userSession;
	}

	public FileDataModel getFileDataModel() {
		return fileDataModel;
	}

	public ShowFile getSelectedFile() {
		return selectedFile;
	}

	public void setSelectedFile(ShowFile selectedFile) {
		this.selectedFile = selectedFile;
	}

	public MongoFileAO getFileAO() {
		return fileAO;
	}
	
	public void setFileAO(MongoFileAO fileAO) {
		this.fileAO = fileAO;
	}
	
	public List<ShowFile> getDropedFiles() {
		return dropedFiles;
	}
	
	public StreamedContent getZipDownloadFile() {
		if(dropedFiles.size() == 0) {
			//add error handling
			return null;
		}
		
		try {
			InputStream in = null;
			File file = new File(MongoConst.TEMP_PATH + userSession.getUsername() + ".zip");
			file.createNewFile();
		
			ZipOutputStream zipOutputStream = new ZipOutputStream(new FileOutputStream(file));
			
			String name;
			int read;
			byte[] bytes = new byte[1024];
			for(ShowFile showFile : dropedFiles) {
				name = showFile.getFileName();
				in = fileAO.readFileByUser(userSession.getUsername(), name);
				zipOutputStream.putNextEntry(new ZipEntry(name));
				while ((read = in.read(bytes)) != -1) {
					zipOutputStream.write(bytes, 0, read);
				}
				in.close();
			}
			zipOutputStream.close();
		
			FileInputStream inputStream = new FileInputStream(file);
			file.delete();
			return new DefaultStreamedContent(
					inputStream, 
					new MimetypesFileTypeMap().getContentType(file), 
					userSession.getUsername() + ".zip");
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return null;
	}
	
	public StreamedContent getDownloadFile() {
		try {
			String fileName = selectedFile.getFileName();
			InputStream inputStream = fileAO.readFileByUser(
					userSession.getUsername(), fileName);
			return new DefaultStreamedContent(
					inputStream, 
					new MimetypesFileTypeMap().getContentType(fileName), 
					fileName);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return null;
	}
	
	public void deleteFile() {
		fileAO.deleteFileInDB(
				userSession.getUsername(),
				selectedFile.getFileName());
		fileDataModel = new FileDataModel(
				fileAO.getFileNamesFor(
						userSession.getUsername()));
	}
}

GruppenarbeitTillChristian/src/application/filemanager/FileUploadBean.java
package application.filemanager;

import java.io.IOException;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import org.primefaces.event.FileUploadEvent;

import application.database.MongoFileAO;
import application.session.UserSession;

@ManagedBean
@SessionScoped
public class FileUploadBean {
	@ManagedProperty(value="#{mongoFileAO}")
	private MongoFileAO fileAO;

	@ManagedProperty(value="#{userSession}")
	private UserSession userSession;
	
	public void handleFileUpload(FileUploadEvent event) {
		try {
			fileAO.writeFileToDB(
					event.getFile().getInputstream(),
					event.getFile().getFileName(),
					userSession.getUsername());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public MongoFileAO getFileAO() {
		return fileAO;
	}

	public void setFileAO(MongoFileAO fileAO) {
		this.fileAO = fileAO;
	}

	public UserSession getUserSession() {
		return userSession;
	}

	public void setUserSession(UserSession userSession) {
		this.userSession = userSession;
	}
}

GruppenarbeitTillChristian/src/application/login/LoginBean.java
package application.login;

import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import application.database.MongoUserAO;
import application.datamodel.User;
import application.session.UserSession;

@ViewScoped
@ManagedBean
public class LoginBean {
	@ManagedProperty(value = "#{mongoUserAO}")
	private MongoUserAO mongoUserAO;
	
	
	@ManagedProperty(value = "#{userSession}")
	private UserSession userSession;

	private String username;
	private String password;

	public String login() {
		User loggedInUser = mongoUserAO.getUser(username, password);
		if(loggedInUser != null) {
			userSession.setUser(loggedInUser);
		}
		
		return "fileoverview";
	}

	public void validateLogin(FacesContext context, UIComponent component,
			Object value) {
		
		UIInput usernameComponent = (UIInput) component.getAttributes().get(
				"usernameForValidator");
		Object usernameFromValidatorValue = usernameComponent.getValue();
		String usernameFromValidator = 	usernameFromValidatorValue.toString();
				

		String passwordFromValidator = value.toString();

		User loggedInUser = mongoUserAO.getUser(usernameFromValidator,
				passwordFromValidator);

		if (loggedInUser == null) {
			
			ResourceBundle bundle = ResourceBundle.getBundle("language.error", context.getViewRoot().getLocale());
		    
			
			FacesMessage message = new FacesMessage(bundle.getString("login_failed"));
			message.setSeverity(FacesMessage.SEVERITY_ERROR);
			throw new ValidatorException(message);
		}
	}
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public MongoUserAO getMongoUserAO() {
		return mongoUserAO;
	}

	public void setMongoUserAO(MongoUserAO mongoUserAO) {
		this.mongoUserAO = mongoUserAO;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public UserSession getUserSession() {
		return userSession;
	}

	public void setUserSession(UserSession userSession) {
		this.userSession = userSession;
	}

	
	

}

GruppenarbeitTillChristian/src/application/login/RegisterBean.java
package application.login;

import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import application.database.MongoUserAO;

@ViewScoped
@ManagedBean
public class RegisterBean {
	@ManagedProperty(value = "#{mongoUserAO}")
	private MongoUserAO mongoUserAO;
	

	private String username;
	private String password;
	private String email;




	public String register() {
		mongoUserAO.addUser(username, password, email);
		return "login";
	}

	
	
	public void validateUsername(FacesContext context, UIComponent component,
			Object value) {
		
		boolean doesExist = mongoUserAO.isUserAlreadyExisting(value.toString());
				

		if (doesExist == true) {
			
			ResourceBundle bundle = ResourceBundle.getBundle("language.error", context.getViewRoot().getLocale());
		    
			
			FacesMessage message = new FacesMessage(bundle.getString("username_already_used"));
			message.setSeverity(FacesMessage.SEVERITY_ERROR);
			throw new ValidatorException(message);
		}
	}
	
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public MongoUserAO getMongoUserAO() {
		return mongoUserAO;
	}

	public void setMongoUserAO(MongoUserAO mongoUserAO) {
		this.mongoUserAO = mongoUserAO;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	
	

}

GruppenarbeitTillChristian/WebContent/fileoverview.xhtml
<ui:composition template="templateLogInRequired.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="title"><h:outputText value="#{msg.file_overview_title}"/></ui:define>
	
	<ui:define name="loginContent">
		<h:form id="form">
			<p:fieldset legend="#{msg.yourFiles}">
				<p:dataTable id="availableFiles" var="file" value="#{fileOverviewBean.fileDataModel}" rows="20"
					selection="#{fileOverviewBean.selectedFile}" selectionMode="single" emptyMessage="#{msg.empty_datatable}"
					paginator="true">
					<p:ajax event="rowSelect" update=":form:dialogDisplay" oncomplete="PF('fileDetail').show();"/>
					
					<p:column style="width:20px">
						<h:outputText id="dragIcon"
							styleClass="ui-icon ui-icon-arrow-4"/>
						<p:draggable for="dragIcon" revert="true"/>
					</p:column>
					
					<p:column headerText="#{msg.fileCollHeaderName}">
						#{file.fileName}
					</p:column>
				</p:dataTable>
			</p:fieldset>
			
			<p:fieldset id="selectedFiles" legend="#{msg.download}">
				<p:commandButton id="download" value="#{msg.download}" ajax="false" icon="ui-icon-arrowthick-s">
					<p:fileDownload value="#{fileOverviewBean.zipDownloadFile}"/>
				</p:commandButton>
				
				<p:outputPanel id="dropArea">
					<h:outputText value="#{msg.clearDownloadDropArea}" rendered="#{empty fileOverviewBean.dropedFiles}" />
					
					<p:dataTable var="file" value="#{fileOverviewBean.dropedFiles}"
						rendered="#{not empty fileOverviewBean.dropedFiles}" rows="10"
						paginator="true">
						
						<p:column headerText="#{msg.fileCollHeaderName}">
							#{file.fileName}
						</p:column>
					</p:dataTable>
				</p:outputPanel>
			</p:fieldset>
			
			<p:droppable for="selectedFiles" tolerance="touch" activeStyleClass="ui-state-highlight"
				datasource="availableFiles">
				<p:ajax listener="#{fileOverviewBean.onDropFile}" update="dropArea"/>
			</p:droppable>
			
			<p:dialog header="#{msg.dialogHeader}" widgetVar="fileDetail" modal="true"
				showEffect="fade" hideEffect="fade" closeOnEscape="true" resizable="false">
				<h:panelGrid id="dialogDisplay">
					<h:panelGrid columns="2">
						<h:outputText value="#{msg.dialogName}:" />
						<h:outputText value="#{fileOverviewBean.selectedFile.fileName}" />
						<p:commandButton id="singleDownload" value="#{msg.download}" ajax="false">
							<p:fileDownload value="#{fileOverviewBean.downloadFile}"/>
						</p:commandButton>
						<p:commandButton id="fileDelete" value="#{msg.delete}" ajax="false"
							actionListener="#{fileOverviewBean.deleteFile}" action="fileoverview"/>
					</h:panelGrid>
				</h:panelGrid>
			</p:dialog>
		</h:form>
	</ui:define>
	
</ui:composition>

GruppenarbeitTillChristian/WebContent/fileupload.xhtml
<ui:composition template="templateLogInRequired.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="title"><h:outputText value="#{msg.file_upload_title}"/></ui:define>
	
	<ui:define name="loginContent">
		<h:form>
			<p:fileUpload fileUploadListener="#{fileUploadBean.handleFileUpload}" mode="advanced"
				dragDropSupport="true" multiple="true" sizeLimit="1000000000" />
		</h:form>
	</ui:define>
	
</ui:composition>

GruppenarbeitTillChristian/WebContent/index.xhtml
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="title"><h:outputText value="#{msg.home}" /></ui:define>
	
	<ui:define name="content">
		<h:outputText value="#{msg.welcome}" />
	</ui:define>
	
</ui:composition>

GruppenarbeitTillChristian/WebContent/login.xhtml
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="title"><h:outputText value="#{msg.home}" /></ui:define>

	<ui:define name="content">
		<h:form>
			<div class="formRow">
				<h:outputLabel value="#{msg.username}" for="username" />
				<h:inputText required="true" value="#{loginBean.username}"
					id="username" requiredMessage="#{err.required}"
					binding="#{usernameForValidator}">

				</h:inputText>
				<h:message for="username" styleClass="formError" />
			</div>

			<div class="formRow">
				<h:outputLabel value="#{msg.password}" for="password" />
				<h:inputSecret required="true" value="#{loginBean.password}"
					requiredMessage="#{err.required}" id="password"
					validator="#{loginBean.validateLogin}">
					<f:attribute name="usernameForValidator"
						value="#{usernameForValidator}" />
				</h:inputSecret>
				<h:message for="password" styleClass="formError" />
			</div>

			<h:commandButton action="#{loginBean.login}" value="#{msg.login}" />
		</h:form>
	</ui:define>

</ui:composition>

GruppenarbeitTillChristian/WebContent/register.xhtml
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="title">
		<h:outputText value="#{msg.home}" />
	</ui:define>

	<ui:define name="content">
		<h:form>
			<div class="formRow">
				<h:outputLabel value="#{msg.username}" for="username" />
				<h:inputText required="true" value="#{registerBean.username}"
					id="username" requiredMessage="#{err.required}"
					validator="#{registerBean.validateUsername}">

				</h:inputText>
				<h:message for="username" styleClass="formError" />
			</div>

			<div class="formRow">
				<h:outputLabel value="#{msg.email}" for="email" />
				<h:inputText required="true" value="#{registerBean.email}"
					id="email" requiredMessage="#{err.required}">
				</h:inputText>
				<h:message for="email" styleClass="formError" />

			</div>
			<div class="formRow">
				<h:outputLabel value="#{msg.password}" for="password1" />
				<p:password id="password1" value="#{registerBean.password}"
					feedback="true" required="true" requiredMessage="#{err.required}"
					goodLabel="#{msg.goodLabel}" weakLabel="#{msg.weakLabel}"
					strongLabel="#{msg.strongLabel}" promptLabel="#{msg.promptLabel}"
					match="password2" label="#{msg.password}">

				</p:password>
				<h:message for="password1" styleClass="formError" />

			</div>
			<div class="formRow">
				<h:outputLabel value="#{msg.passwordRepeat}" for="password2" />
				<p:password id="password2" value="#{registerBean.password}"
					required="true" requiredMessage="#{err.required}"
					label="#{msg.passwordRepeat}">

				</p:password>
				<h:message for="password2" styleClass="formError" />
			</div>

			<h:commandButton action="#{registerBean.register}"
				value="#{msg.register}" />
		</h:form>
	</ui:define>

</ui:composition>

GruppenarbeitTillChristian/WebContent/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Cloud - <ui:insert name="title" /></title>
	<link
		href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
		rel="stylesheet" />
	<meta name="viewport" content="width=device-width" />

	<ui:insert name="sideTags" />
</h:head>

<h:body>
	<div class="root">
		<h:form>
			<div class="topbar">

				<div class="siteTitle">
					<h:commandLink action="index">
						<h:outputText value="#{msg.sitename}"></h:outputText>
						<i class="fa fa-save"></i>
					</h:commandLink>
				</div>


				<div class="screenTitle">
					<h2>
						<ui:insert name="title" />
					</h2>
				</div>
				<div class="userActions">
					<ui:fragment rendered="#{userSession.loggedIn}">

						<div class="userName">
							<h:commandLink action="index">
								<i class="fa fa-user fa-lg" />
								<h:outputText value="#{userSession.username}" />
							</h:commandLink>
						</div>

						<div class="logout">
							<h:commandLink action="#{userSession.loggingOut}">
								<i class="fa fa-lock fa-lg"></i>
								<h:outputText value="#{msg.logout}" />
							</h:commandLink>
						</div>

					</ui:fragment>

					<ui:fragment rendered="#{!userSession.loggedIn}">
						<div class="logout">
							<h:commandLink action="login">
								<i class="fa fa-lock fa-lg"></i>
								<h:outputText value="#{msg.login}" />
							</h:commandLink>
						</div>
					</ui:fragment>
				</div>


			</div>
		</h:form>
		<div class="contentContainer">
			<div class="content">
				<ui:insert name="content" />
			</div>

			<div class="side sidebar">

				<ui:insert name="sidebar" />

			</div>

			<div class="menu side">
				<h:form>
					<ul>
						<ui:fragment rendered="#{!userSession.loggedIn}">
							<li><h:commandLink value="#{msg.register}" action="register" /></li>
						</ui:fragment>

						<ui:fragment rendered="#{userSession.loggedIn}">
							<li><h:commandLink value="#{msg.fileoverview}"
									action="fileoverview" /></li>
							<li><h:commandLink value="#{msg.fileupload}"
									action="fileupload" /></li>
						</ui:fragment>

						<ui:insert name="aditionalMenuItems" />
					</ul>
				</h:form>
			</div>
		</div>
	</div>
	<div class="footer">
		<h:outputText value="#{msg.footer_text}"></h:outputText>
	</div>
</h:body>

<link rel="stylesheet" type="text/css" href="style/main.css" />

</html>

GruppenarbeitTillChristian/WebContent/templateLogInRequired.xhtml
<ui:composition template="template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	
	<ui:define name="content">
		<ui:fragment rendered="#{userSession.loggedIn}">
			<ui:insert name="loginContent" />
		</ui:fragment>
		<ui:fragment rendered="#{!userSession.loggedIn}">
			<h:outputText value="#{msg.please_login}" />
<!-- 			Link zur login Seite -->
			<ui:insert name="additionalLogoutContent" />
		</ui:fragment>
	</ui:define>
</ui:composition>